load("@rules_python//python/entry_points:py_console_script_binary.bzl", "py_console_script_binary")

package(default_visibility = ["//:__subpackages__"])

py_console_script_binary(
    name = "pyside6-qmllint",
    pkg = "@pip//pyside6_essentials:pkg",
    script = "pyside6-qmllint",
)
