# RuboCop configuration for rules_lint example

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

# Configure line length
Layout/LineLength:
  Max: 100

# Enable some common cops for demonstration
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Lint/UselessAssignment:
  Enabled: true

Style/DoubleNegation:
  Enabled: true
