# Standard Ruby configuration for rules_lint example
#
# Standard Ruby is a zero-configuration Ruby style guide, linter, and formatter
# based on RuboCop. See https://github.com/standardrb/standard
#
# This file allows minimal customization of Standard Ruby's opinionated defaults.

# Configure target Ruby version
ruby_version: 3.0

# Ignore certain paths (glob patterns)
ignore:
  - 'vendor/**/*'
  - 'tmp/**/*'

# You can configure specific cops if needed, though Standard discourages this
# fix: false  # Uncomment to prevent auto-fixing
# parallel: true  # Uncomment to enable parallel processing
