package(default_visibility = ["//visibility:public"])

exports_files(
    [
        ".rubocop.yml",
        ".standard.yml",
        "Gemfile",
        "Gemfile.lock",
        ".ruby-version",
    ],
    visibility = ["//visibility:public"],
)
