load("@aspect_rules_lint//format:defs.bzl", "format_multirun")

package(default_visibility = ["//:__subpackages__"])

format_multirun(
    name = "format",
    pkl = "@rules_pkl//pkl",
    visibility = ["//:__subpackages__"],
)
