load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "widget_proto",
    srcs = ["widget.proto"],
    strip_import_prefix = "/modules/fixtures",
)
