load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

exports_files(["ruff.toml"])

py_library(
    name = "unused_import",
    srcs = ["unused_import.py"],
)
