package(default_visibility = ["//visibility:public"])

filegroup(
    name = "bad",
    srcs = ["bad.md"],
    tags = ["markdown"],
)

filegroup(
    name = "good",
    srcs = ["good.md"],
    tags = ["markdown"],
)

filegroup(
    name = "link_targets",
    srcs = ["target.md"],
)
