package(default_visibility = ["//visibility:public"])

filegroup(
    name = "bad",
    srcs = ["bad.md"],
    tags = ["markdown"],
)

filegroup(
    name = "combined",
    srcs = [
        "bad.md",
        "bad_local.md",
    ],
    tags = ["markdown"],
)

filegroup(
    name = "good",
    srcs = ["good.md"],
    tags = ["markdown"],
)

filegroup(
    name = "lowercase_r_markdown_bad",
    srcs = ["lowercase_r_markdown_bad.rmd"],
    tags = ["markdown"],
)

filegroup(
    name = "link_targets",
    srcs = ["target.md"],
)
