# See https://github.com/bazel-contrib/publish-to-bcr
name: Publish to BCR

on:
  # Run the publish workflow after a successful release
  # Can be triggered from the release.yaml workflow
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  # In case of problems, let release engineers retry by manually dispatching
  # the workflow from the GitHub UI
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@67dd6be95d330b42a43c1cb28e48b21a8e60f4ea # 2025 March 14
    with:
      tag_name: ${{ inputs.tag_name }}
      # GitHub repository which is a fork of the upstream where the Pull Request will be opened.
      registry_fork: aspect-build/bazel-central-registry
    permissions:
      contents: write
    secrets:
      publish_token: ${{ secrets.PUBLISH_TOKEN }}
